version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx_2.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
